apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: ceph-exporter
  name: ceph-exporter
spec:
  clusterIP: None
  ports:
  - name: ceph-exporter
    port: 9128
    protocol: TCP
  selector:
    app: ceph-exporter
  type: ClusterIP